<a href="https://colab.research.google.com/github/Ihbar1/ihbar.github.io/blob/main/1930511043_Ihbar_Madyan_R_Teknik_Informatika_6A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
# data diambil berdasarkan soal

import pandas as pd

hp = {
    'RAM' : [8,4,8,8,8,8,6,8,4,6,6,8,3,3,4,8,8,4,6,3],
    'Harga': [4299000,2439000,4360000,5999000,4950000,4599000,5600000,
              5199000,2099000,2679000,2965000,2880000,1450000,1640000,
              2400000,3749000,4500000,2319000,3359000,1425000],
    'Brand': ['Oppo','Oppo','Oppo','Oppo','Oppo','Samsung Galaxy','Samsung Galaxy',
              'Samsung Galaxy','Samsung Galaxy','Samsung Galaxy','Oppo','Oppo',
              'Oppo','Oppo','Oppo','Samsung Galaxy','Samsung Galaxy','Samsung Galaxy',
              'Samsung Galaxy','Samsung Galaxy']
    }

hp_df = pd.DataFrame(hp)
hp_df

RAM    Harga           Brand
0     8  4299000            Oppo
1     4  2439000            Oppo
2     8  4360000            Oppo
3     8  5999000            Oppo
4     8  4950000            Oppo
5     8  4599000  Samsung Galaxy
6     6  5600000  Samsung Galaxy
7     8  5199000  Samsung Galaxy
8     4  2099000  Samsung Galaxy
9     6  2679000  Samsung Galaxy
10    6  2965000            Oppo
11    8  2880000            Oppo
12    3  1450000            Oppo
13    3  1640000            Oppo
14    4  2400000            Oppo
15    8  3749000  Samsung Galaxy
16    8  4500000  Samsung Galaxy
17    4  2319000  Samsung Galaxy
18    6  3359000  Samsung Galaxy
19    3  1425000  Samsung Galaxy

In [36]:
# Preprocessing data bertujuan untuk data bersih dari noise  
# dan data lebih terstruktur

import numpy as np 

x_train = np.array(hp_df[['RAM', 'Harga']])
y_train = np.array(hp_df['Brand'])

print(f'X_train:\n{x_train}\n')
print(f'Y_train:\n{y_train}\n')

X_train:
[[      8 4299000]
 [      4 2439000]
 [      8 4360000]
 [      8 5999000]
 [      8 4950000]
 [      8 4599000]
 [      6 5600000]
 [      8 5199000]
 [      4 2099000]
 [      6 2679000]
 [      6 2965000]
 [      8 2880000]
 [      3 1450000]
 [      3 1640000]
 [      4 2400000]
 [      8 3749000]
 [      8 4500000]
 [      4 2319000]
 [      6 3359000]
 [      3 1425000]]

Y_train:
['Oppo' 'Oppo' 'Oppo' 'Oppo' 'Oppo' 'Samsung Galaxy' 'Samsung Galaxy'
 'Samsung Galaxy' 'Samsung Galaxy' 'Samsung Galaxy' 'Oppo' 'Oppo' 'Oppo'
 'Oppo' 'Oppo' 'Samsung Galaxy' 'Samsung Galaxy' 'Samsung Galaxy'
 'Samsung Galaxy' 'Samsung Galaxy']



In [37]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
print (f'y_train:\n{y_train}')

y_train:
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [38]:
# hasil yang didapat 0 1 berupa brand 0 = Oppo dan 1 = Samsung Galaxy

y_train = y_train.flatten()
print(f'y_train: {y_train}')

y_train: [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1]


In [39]:
# Menentukan K atau tetangga terdekatnya yaitu berjumlah 3

from sklearn.neighbors import KNeighborsClassifier

K=3

model = KNeighborsClassifier(n_neighbors=K)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [40]:
# Memasukan data baru yang akan ditentukan brandnya berdasar RAM dan Harga

RAM = 8
Harga = 3800000
x_new = np.array([RAM, Harga]).reshape(1, -1)
x_new

array([[      8, 3800000]])

In [41]:
# Memprediksi brand berdasar data baru yang telah dimasukan

y_new = model.predict(x_new)
y_new

array([1])

In [42]:
# yaitu data tersebut memiliki kedekatan dengan brand Samsung

lb.inverse_transform(y_new)

array(['Samsung Galaxy'], dtype='<U14')

In [43]:
# Dihitung secara Manual

hp_manual = np.array([RAM, Harga ])
hp_manual

array([      8, 3800000])

In [44]:
# Menentukan secara manual jarak data baru dihitung berdasarkan jarak terdekatnya (Euclidean) 

from scipy.spatial.distance import euclidean

jarak_data = [euclidean(hp_manual, d) for d in x_train]
jarak_data

[499000.0,
 1361000.000005878,
 560000.0,
 2199000.0,
 1150000.0,
 799000.0,
 1800000.000001111,
 1399000.0,
 1701000.0000047032,
 1121000.0000017842,
 835000.0000023952,
 920000.0,
 2350000.0000053192,
 2160000.0000057872,
 1400000.0000057144,
 51000.0,
 700000.0,
 1481000.0000054017,
 441000.00000453513,
 2375000.0000052634]

In [45]:
# Sehingga Data Terurut berdasar data terdekat karena K = 3 
# maka yang diambil 3 teratas dan hasilnya dominan Samsung Galaxy 2 dan Oppo 1

hp_df['euclidean'] = jarak_data
hp_df.sort_values(['euclidean'])

RAM    Harga           Brand     euclidean
15    8  3749000  Samsung Galaxy  5.100000e+04
18    6  3359000  Samsung Galaxy  4.410000e+05
0     8  4299000            Oppo  4.990000e+05
2     8  4360000            Oppo  5.600000e+05
16    8  4500000  Samsung Galaxy  7.000000e+05
5     8  4599000  Samsung Galaxy  7.990000e+05
10    6  2965000            Oppo  8.350000e+05
11    8  2880000            Oppo  9.200000e+05
9     6  2679000  Samsung Galaxy  1.121000e+06
4     8  4950000            Oppo  1.150000e+06
1     4  2439000            Oppo  1.361000e+06
7     8  5199000  Samsung Galaxy  1.399000e+06
14    4  2400000            Oppo  1.400000e+06
17    4  2319000  Samsung Galaxy  1.481000e+06
8     4  2099000  Samsung Galaxy  1.701000e+06
6     6  5600000  Samsung Galaxy  1.800000e+06
13    3  1640000            Oppo  2.160000e+06
3     8  5999000            Oppo  2.199000e+06
12    3  1450000            Oppo  2.350000e+06
19    3  1425000  Samsung Galaxy  2.375000e+06

In [46]:
X_test = np.array([[6, 3359000], [4, 2439000], [3,1300000], [6, 5600000], [4, 2299000], [3, 1350000]])
Y_test = lb.transform(np.array(['Samsung Galaxy', 'Oppo', 'Oppo', 'Samsung Galaxy', 'Oppo', 'Samsung Galaxy']))

print (f'X_test:\n{X_test}')
print (f'Y_test:\n{Y_test}')

X_test:
[[      6 3359000]
 [      4 2439000]
 [      3 1300000]
 [      6 5600000]
 [      4 2299000]
 [      3 1350000]]
Y_test:
[[1]
 [0]
 [0]
 [1]
 [0]
 [1]]


In [47]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0])

In [48]:
#accuracy

from sklearn.metrics import accuracy_score

acc = accuracy_score(Y_test, y_pred)

print (f'Accuracy : {acc}')

Accuracy : 0.8333333333333334
