<a href="https://colab.research.google.com/github/Ihbar1/ihbar.github.io/blob/main/praktikum_klasisfikasi_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

baju ={
    'tinggi badan(cm)':[160,160,160,160,165,
                        165,165,165,170,170,
                        170,175,175,180,180],
    'berat badan(kg)' :[45,50,56,65,50,
                        58,60,67,50,65,
                        75,60,70,58,70],
    'size': ['m','m','l','l','m',
             'm','l','l','l','l',
             'l','l','l','l','l']
}
baju_df = pd.DataFrame(baju)
baju_df

tinggi badan(cm)  berat badan(kg) size
0                160               45    m
1                160               50    m
2                160               56    l
3                160               65    l
4                165               50    m
5                165               58    m
6                165               60    l
7                165               67    l
8                170               50    l
9                170               65    l
10               170               75    l
11               175               60    l
12               175               70    l
13               180               58    l
14               180               70    l

In [9]:
import numpy as np

x_train = np.array(baju_df[['tinggi badan(cm)','berat badan(kg)']])
y_train = np.array(baju_df['size'])

print(f'x_train:\n{x_train}\n')
print(f'y_train:{y_train}')

x_train:
[[160  45]
 [160  50]
 [160  56]
 [160  65]
 [165  50]
 [165  58]
 [165  60]
 [165  67]
 [170  50]
 [170  65]
 [170  75]
 [175  60]
 [175  70]
 [180  58]
 [180  70]]

y_train:['m' 'm' 'l' 'l' 'm' 'm' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l']


In [13]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
print(f'y_train:\n{y_train}')

y_train:
[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [14]:
y_train= y_train.flatten()
print(f'y_train:{y_train}')

y_train:[1 1 0 0 1 1 0 0 0 0 0 0 0 0 0]


In [20]:
from sklearn.neighbors import KNeighborsClassifier
k=3
model=KNeighborsClassifier(n_neighbors=k)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
tinggi_badan = 163
berat_badan = 70
x_new = np.array([tinggi_badan,berat_badan]).reshape(1,-1)
x_new 

array([[163,  70]])

In [23]:
y_new = model.predict(x_new)
y_new

array([0])

In [26]:
lb.inverse_transform(y_new)

array(['l'], dtype='<U1')

In [27]:
baju_manual = np.array([tinggi_badan,berat_badan])
baju_manual

array([163,  70])

In [28]:
x_train

array([[160,  45],
       [160,  50],
       [160,  56],
       [160,  65],
       [165,  50],
       [165,  58],
       [165,  60],
       [165,  67],
       [170,  50],
       [170,  65],
       [170,  75],
       [175,  60],
       [175,  70],
       [180,  58],
       [180,  70]])

In [29]:
from scipy.spatial.distance import euclidean

jarak_data =[euclidean(baju_manual,d) for d in x_train]
jarak_data

[25.179356624028344,
 20.223748416156685,
 14.317821063276353,
 5.830951894845301,
 20.09975124224178,
 12.165525060596439,
 10.198039027185569,
 3.605551275463989,
 21.18962010041709,
 8.602325267042627,
 8.602325267042627,
 15.620499351813308,
 12.0,
 20.808652046684813,
 17.0]

In [30]:
baju_df['euclidean']= jarak_data
baju_df.sort_values(['euclidean'])

tinggi badan(cm)  berat badan(kg) size  euclidean
7                165               67    l   3.605551
3                160               65    l   5.830952
9                170               65    l   8.602325
10               170               75    l   8.602325
6                165               60    l  10.198039
12               175               70    l  12.000000
5                165               58    m  12.165525
2                160               56    l  14.317821
11               175               60    l  15.620499
14               180               70    l  17.000000
4                165               50    m  20.099751
1                160               50    m  20.223748
13               180               58    l  20.808652
8                170               50    l  21.189620
0                160               45    m  25.179357

In [32]:
x_test =np.array([[160,55],[165,58],[175,70],[180,73]])
y_test = lb.transform(np.array(['m','m','l','l'])).flatten()

print(f'x_test:\n{x_test}\n')
print(f'y_test:\n{y_test}\n')

x_test:
[[160  55]
 [165  58]
 [175  70]
 [180  73]]

y_test:
[1 1 0 0]

